export const LOGIN_URL = "user/login";
export const SIGNUP_URL = "user/SignUp";
export const UPDATE_PROFILE = "user/updateProfile";
export const DELETE_USER = "user/deleteUser";
export const DRAWER_BODY_PARTS = "bodyPart/getAllBodyParts";
export const GET_ALL_EXERCISE = "workout/allWorkoutSpecificCategory";
export const GET_WORKOUT_DETAILS = "workout/getWorkoutDetail";
export const GET_DRAWER_EXERCISE = "exercise/myExercise";
export const GET_SPECIFIC_DRAWER_EXERCISE = "exercise/specificExercise";
export const GET_AFFLIATE_PRODUCT = "affiliateProduct/getAffliateProduct";
export const ALL_DIETS = "recipe/allDiets";
export const GET_SPECIFIC_DIETS = "recipe/specificDietDetail";
export const ALL_CATEGORY_DIETS = "recipe/AllcategoryDiets";
export const SPECIFIC_CATEGORY_DATA = "recipe/specificCategoryData";
export const DIET_FAVOURITE = "recipe/dietFavourite";
export const GET_DIET_FAVOURITE = "recipe/getdietFavourite";
export const GET_ALL_BLOG = "post/getAllPost";
export const GET_ALL_EXERCISES = "workout/allWorkoutSpecificCategory";
export const GET_ALL_TAGS = "tag/getAllTag";
export const CATEGORY_BLOG = "post/categoryBlog";
export const GET_PRODUCT_TYPE = "productType/getProductType";
export const GET_PRODUCTS_BY_TYPE = "affiliateProduct/getProductsByType";
export const GET_PLANS = "plan/getPlans";
export const ADD_FAV_PLAN = "plan/addFavPlan";
export const GET_ALL_FAV_PLANS = "plan/getAllFavPlan";

//yhn end points dal dena